name: scp files to production
on: 
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@master
    # - name: aba444.com
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: 104.248.151.9
    #     username: aba444
    #     password: "~b47gr6H2"
    #     port: 22
    #     source: "*"
    #     target: "/var/www/vhosts/aba444.com/member.aba444.com"

    - uses: actions/checkout@master
    - name: aba567.com
      uses: appleboy/scp-action@master
      with:
        host: 68.183.232.127
        username: aba567.com_2zt81dttulp
        password: "Wr13m4e5_"
        port: 22
        source: "*"
        target: "/var/www/vhosts/aba444.com/member.aba567.com"

    - name: curl
      uses: wei/curl@master
      with:
        args: https://member.aba567.com/update.php