name: scp files to production
on: 
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: aba444.com
      uses: appleboy/scp-action@master
      with:
        host: 104.248.151.9
        username: root
        password: "bqHzmVDL36RY9RGp"
        port: 22
        source: "*"
        target: "/var/www/vhosts/aba444.com/member.aba444.com"