name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: github action runner
      uses: appleboy/scp-action@master
      with:
        host: 165.232.164.156
        username: root
        password: "@Aa123456Aa"
        port: 22
        source: "*"
        target: "/var/www/dev.aba444.com"
        
    - uses: actions/checkout@master    
    - name: "dev.aba444.com"
      uses: appleboy/scp-action@master
      with:
        host: dev.aba444.com
        username: root
        password: "bqHzmVDL36RY9RGp"
        port: root
        source: "*"
        target: "/var/www/vhosts/aba444.com/dev.aba444.com"
